### ISSUE TITLE
[Certificados] Revisar como se realiza el query aquí para que solo te muestre los tuyos

### ISSUE THREAD

**Issue by danteese** [danteese/suuma_service#16]
Creo que aquí te muestra TODOS...

![Captura de Pantalla 2020-06-23 a la(s) 9 55 17](https://user-images.githubusercontent.com/20823315/85419475-c15abf00-b537-11ea-85b4-f9a2ee961626.png)

**Comment by bvideal** [comment]
El query para Certtificados ahora solamente muestra los certificados personales.
