### ISSUE TITLE
[Certificados] Se ven muy chicas las letras

### ISSUE THREAD

**Issue by danteese** [danteese/suuma_service#17]
Utilizar formatos para que se vean de acuerdo a lo que se necesita, como si fueran campos.

![Captura de Pantalla 2020-06-23 a la(s) 9 56 43](https://user-images.githubusercontent.com/20823315/85419580-e3ecd800-b537-11ea-88d6-fe98101d0249.png)

> Así se ve una vista de detalle de una guardia:

![Captura de Pantalla 2020-06-23 a la(s) 9 59 18](https://user-images.githubusercontent.com/20823315/85419948-4219bb00-b538-11ea-91cc-30e53bc6abe6.png)

**Comment by bvideal** [comment]
Reconstruccion de la pagina de detalles para ser mas leible.

**Comment by danteese** [comment]
Se que esos son de prueba, pero sería bueno que entonces cargaras alguno por defecto en el storage y lo mostraras, cuando no hay un archivo esto debería mandar a 404 porque sino siempre va a decir que existe... y eso no queremos porque es falso, en realidad no existe, el path debería de traer información más relevante y esto viene desde la función en CertificateController@showFile o se regresa que no existe o tu desde el lado del cliente te previenes cuando regresas null 

<img width="696" alt="Captura de Pantalla 2020-06-29 a la(s) 0 01 16" src="https://user-images.githubusercontent.com/20823315/85974706-d69e7600-b99b-11ea-8de0-ad2e4b687127.png">


<img width="1391" alt="Captura de Pantalla 2020-06-28 a la(s) 23 54 15" src="https://user-images.githubusercontent.com/20823315/85974558-67288680-b99b-11ea-9c53-22a5b5e490d8.png">
