### ISSUE TITLE
Detalles en certificados

### ISSUE THREAD

**Issue by danteese** [danteese/suuma_service#22]
- [x] Cambiar regresar por guardar
- [x] Aumentar el tamaño de la vista previa del documento
- [x] Verificar la ruta de donde se extrae el archivo

**Comment by bvideal** [comment]
- Se cambio "regresar" por "aceptar" en el dialogo de insercion de archivos.
- Se cambia el tama;o del dialogo y el tag de html que carga la imagen cuando ya se ha insertado una imagen al sistema.
- La ruta ahora es absoluta para poder hacer rendering del archivo desde admin o personales.

- Nombre completo del usuario en el certificado

- Se pueden cancelar los certificados previamente aprobados.

**Comment by danteese** [comment]
A pesar de que ya cambia dependiendo del tamaño aún no hay una retroalimentación para el usuario en la parte de adjuntar archivo, recomiendo ver https://medium.com/js-dojo/upload-files-to-cloudinary-using-vue-vuetify-dd45472c4fd6

Que se resume en esta respuesta (pero es bueno aprender cosas nuevas): 
https://stackoverflow.com/a/50900809/8567062


<img width="976" alt="Captura de Pantalla 2020-06-28 a la(s) 23 33 32" src="https://user-images.githubusercontent.com/20823315/85973344-1a8f7c00-b998-11ea-95ff-e46e1b92ab9f.png">
<img width="837" alt="Captura de Pantalla 2020-06-28 a la(s) 23 33 44" src="https://user-images.githubusercontent.com/20823315/85973343-18c5b880-b998-11ea-944e-4d512e520c83.png">
